### ISSUE TITLE
Civil War in the Middle East and North Africa

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#1165]
This issue is a merger of the following issues
- [ ] [Libyan Civil Wars](https://github.com/simsulla/nwomod/issues/778)
- [ ] [Afghan Civil Wars from 1992 to Present Day](https://github.com/simsulla/nwomod/issues/863)
- [ ] [Somalian Civil War](https://github.com/simsulla/nwomod/issues/585)
- [ ] [Lebanese Civil War](https://github.com/simsulla/nwomod/issues/880)

**Comment by arandomperson5000** [comment]
Given the nature of clan politics in Somalia, I intend to split up up the Somali culture to multiple culture representing Somali clans like the Isaaq, Darod etc to make a more accurate representation of Somali politics in NWO however the Somali culture would still remain as it represent the Somalis who don't identify with any clan and it function like the Yugoslav culture.
